/** 中文文案集中管理（预留 i18n 扩展） */
export const strings = {
  common: {
    confirm: '确定',
    cancel: '取消',
    retry: '重试',
    loading: '加载中…',
    operationFailed: '操作失败',
    networkError: '无法连接服务器，请检查地址与网络',
    copy: '复制',
    logout: '退出登录',
    settings: '设置',
    back: '返回',
  },
  login: {
    title: '连接 DiceFrame 服务器',
    serverLabel: '服务器地址',
    serverPlaceholder: '例如 192.168.1.5:18000',
    serverPlaceholderWeb: '留空使用当前站点，或输入服务器地址',
    connect: '连接',
    passwordLabel: '访问密码',
    passwordPlaceholder: '服务器访问密码',
    login: '登录',
    enterOpen: '服务器未设密码，直接进入',
    joinInstead: '我是玩家，通过分享链接加入 →',
    serverOk: '服务器连接成功',
    wrongPassword: '密码不正确',
  },
  join: {
    title: '加入对局',
    linkLabel: '粘贴分享链接',
    linkPlaceholder: 'http://192.168.1.5:18000/#/play?game=…',
    parse: '解析链接',
    invalidLink: '链接无效：缺少 game 参数',
    roomPasswordLabel: '房间密码',
    roomPasswordPlaceholder: '本局设置了房间密码',
    verify: '验证并继续',
    reclaimIdentity: '找回我的角色',
    newNameLabel: '角色名',
    newNamePlaceholder: '为新角色起个名字',
    createCharacter: '创建角色并加入',
    joined: '已加入对局',
  },
  overview: {
    title: '我的对局',
    empty: '还没有对局，点击右上角 + 创建第一个对局',
    deleteTitle: '删除对局？',
    deleteMessage: '删除后将无法恢复该对局存档。',
    batchDeleteTitle: '删除所选对局？',
    batchDeleteMessage: '删除后将无法恢复所选对局存档。',
    enter: '进入',
    round: '回合',
    players: '玩家',
    switchServer: '服务器',
    ownerMode: 'GM 模式',
    goToJoin: '玩家加入',
  },
  play: {
    title: '对局',
    gmThinking: 'GM 正在思考…',
    actionPlaceholder: '描述你的行动…',
    send: '发送',
    submitting: '已提交，等待 GM…',
    voiceUnavailable: '服务器未配置语音识别（ASR）',
    recordStart: '按住说话',
    recordStop: '松开发送',
    characterPanel: '角色',
    advance: '推进回合',
    rollback: '回退',
    gmCommand: 'GM 指令',
    gmCommandPlaceholder: '输入 GM 指令…',
    luckSpend: '花费运气重骰',
    luckDecline: '接受结果',
    luckDecisionPending: '等待运气决定',
    resolveLuckFirst: '请先处理本轮运气决定',
    gameEnded: '对局已结束，不能继续提交行动',
    connected: '实时',
    connecting: '连接中…',
    polling: '轮询模式',
    refresh: '刷新',
    loadMore: '加载更早的回合',
    // GM 工具
    recap: '故事摘要',
    recapBusy: '生成中…',
    botBind: '机器人绑定',
    botBindCopied: '绑定指令已复制',
    inviteLink: '邀请链接',
    inviteCopied: '邀请链接已复制',
    mode: '模式',
    modeSolo: '单人',
    modeMulti: '多人',
    access: '访问控制',
    accessOpen: '开放',
    accessClosed: '关闭',
    roomPassword: '房间密码',
    worldSwitch: '世界观',
    export: '导出存档',
    exportDialogTitle: '分享 DiceFrame 存档',
    reset: '重置进度',
    resetTitle: '重置对局进度？',
    resetMessage: '这会清除当前对局进度，且无法恢复。',
    restart: '重启对局',
    restartTitle: '重启对局？',
    restartMessage: '这会重新启动当前对局流程。',
    perception: '私信',
    perceptionPlaceholder: '向角色发送私信…',
    // 多人管理
    playerList: '玩家列表',
    away: '暂离',
    back: '回归',
    kick: '移除',
    kickTitle: '移除玩家？',
    kickMessage: '移除后该玩家将离开当前对局。',
    copyLink: '复制链接',
    acted: '已行动',
    waitingAction: '等待行动',
    needsRoll: '待骰',
    awayFollowing: '暂离中',
    // 健康面板
    health: '系统状态',
    unhandledIssues: '待处理问题',
    resolved: '已解决',
    ignore: '忽略',
    noHealthEvents: '暂无系统事件',
    round: '回合',
    phase: '阶段',
    players: '玩家',
    // 世界观切换
    switchWorldTitle: '切换世界观',
    currentWorld: '当前世界',
    templateSource: '模板',
    lorebookSource: '世界书',
    // 角色卡
    characterCards: '角色卡库',
    selectCard: '选择角色卡',
    // 规则帮助
    ruleHelp: '规则帮助',
    // 场景图
    sceneGallery: '场景图集',
    sceneImageManage: '场景图管理',
    mapBackgroundManage: '地图背景管理',
  },
  map: {
    title: '场景地图',
    workspaceTitle: '冒险地图',
    searchPlaceholder: '搜索地点或关键词',
    locations: '地点列表',
    locationCount: '{count} 个地点',
    currentLocation: '当前位置',
    sourceLorebook: '世界书',
    sourcePlugin: '内容包',
    connections: '相连地点',
    keywords: '相关关键词',
    noDescription: '这个地点还没有详细介绍。',
    noSearchResults: '没有匹配的地点。',
    noMapData: '暂无地图数据',
    recenter: '回到当前场景',
    close: '关闭',
  },
  errors: {
    micDenied: '麦克风权限被拒绝，请在系统设置中允许',
    recordFailed: '录音失败，请重试',
    asrFailed: '语音识别失败',
    emptyRecording: '录音太短，请重试',
  },
} as const
