/** 中文文案集中管理（预留 i18n 扩展） */
export const strings = {
  common: {
    confirm: '确定',
    cancel: '取消',
    retry: '重试',
    loading: '加载中…',
    operationFailed: '操作失败',
    networkError: '无法连接服务器，请检查地址与网络',
    copy: '复制',
    logout: '退出登录',
    settings: '设置',
    back: '返回',
  },
  login: {
    title: '连接 DiceFrame 服务器',
    serverLabel: '服务器地址',
    serverPlaceholder: '例如 192.168.1.5:18000',
    connect: '连接',
    passwordLabel: '访问密码',
    passwordPlaceholder: '服务器访问密码',
    login: '登录',
    enterOpen: '服务器未设密码，直接进入',
    joinInstead: '我是玩家，通过分享链接加入 →',
    serverOk: '服务器连接成功',
    wrongPassword: '密码不正确',
  },
  join: {
    title: '加入对局',
    linkLabel: '粘贴分享链接',
    linkPlaceholder: 'http://192.168.1.5:18000/#/play?game=…',
    parse: '解析链接',
    invalidLink: '链接无效：缺少 game 参数',
    roomPasswordLabel: '房间密码',
    roomPasswordPlaceholder: '本局设置了房间密码',
    verify: '验证并继续',
    reclaimIdentity: '找回我的角色',
    newNameLabel: '角色名',
    newNamePlaceholder: '为新角色起个名字',
    createCharacter: '创建角色并加入',
    joined: '已加入对局',
  },
  overview: {
    title: '我的对局',
    empty: '还没有对局，用 Web 端创建后在这里继续',
    enter: '进入',
    round: '回合',
    players: '玩家',
    switchServer: '服务器',
    ownerMode: 'GM 模式',
    goToJoin: '玩家加入',
  },
  play: {
    title: '对局',
    gmThinking: 'GM 正在思考…',
    actionPlaceholder: '描述你的行动…',
    send: '发送',
    submitting: '已提交，等待 GM…',
    voiceUnavailable: '服务器未配置语音识别（ASR）',
    recordStart: '按住说话',
    recordStop: '松开发送',
    characterPanel: '角色',
    advance: '推进回合',
    rollback: '回退',
    gmCommand: 'GM 指令',
    gmCommandPlaceholder: '输入 GM 指令…',
    luckSpend: '花费运气重骰',
    luckDecline: '接受结果',
    connected: '实时',
    connecting: '连接中…',
    polling: '轮询模式',
    refresh: '刷新',
    loadMore: '加载更早的回合',
  },
  errors: {
    micDenied: '麦克风权限被拒绝，请在系统设置中允许',
    recordFailed: '录音失败，请重试',
    asrFailed: '语音识别失败',
    emptyRecording: '录音太短，请重试',
  },
} as const
