const { withAppBuildGradle } = require('@expo/config-plugins')

const PLUGIN_MARKER = '// DiceFrame release signing (generated by withAndroidReleaseSigning)'

/**
 * Configure an optional Android release upload key without storing credentials
 * in the repository. Values can come from user-level Gradle properties or
 * environment variables with the same names.
 */
module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (configWithGradle) => {
    if (configWithGradle.modResults.language !== 'groovy') {
      throw new Error('DiceFrame Android release signing requires a Groovy app/build.gradle')
    }

    let contents = configWithGradle.modResults.contents
    if (contents.includes(PLUGIN_MARKER)) {
      return configWithGradle
    }

    const androidBlock = 'android {\n    ndkVersion rootProject.ext.ndkVersion'
    if (!contents.includes(androidBlock)) {
      throw new Error('Could not find the Expo Android block for DiceFrame release signing')
    }

    contents = contents.replace(
      androidBlock,
      `${PLUGIN_MARKER}
` +
        `def diceframeSigningValue = { name -> findProperty(name) ?: System.getenv(name) }
` +
        `def diceframeUploadStoreFile = diceframeSigningValue('DICEFRAME_UPLOAD_STORE_FILE')
` +
        `def diceframeUploadStorePassword = diceframeSigningValue('DICEFRAME_UPLOAD_STORE_PASSWORD')
` +
        `def diceframeUploadKeyAlias = diceframeSigningValue('DICEFRAME_UPLOAD_KEY_ALIAS')
` +
        `def diceframeUploadKeyPassword = diceframeSigningValue('DICEFRAME_UPLOAD_KEY_PASSWORD')
` +
        `def diceframeHasReleaseSigning = [
` +
        `    diceframeUploadStoreFile,
` +
        `    diceframeUploadStorePassword,
` +
        `    diceframeUploadKeyAlias,
` +
        `    diceframeUploadKeyPassword,
` +
        `].every { value -> value != null && !value.toString().isBlank() }

` +
        androidBlock,
    )

    const debugSigningConfig = `        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
`
    if (!contents.includes(debugSigningConfig)) {
      throw new Error('Could not find the Expo debug signing config for DiceFrame release signing')
    }

    contents = contents.replace(
      debugSigningConfig,
      `${debugSigningConfig}        release {
` +
        `            if (diceframeHasReleaseSigning) {
` +
        `                storeFile file(diceframeUploadStoreFile)
` +
        `                storePassword diceframeUploadStorePassword
` +
        `                keyAlias diceframeUploadKeyAlias
` +
        `                keyPassword diceframeUploadKeyPassword
` +
        `            }
` +
        `        }
`,
    )

    const debugReleaseSigning = '            signingConfig signingConfigs.debug\n'
    const releaseBlock = '        release {\n'
    const releaseBlockIndex = contents.indexOf(releaseBlock, contents.indexOf('buildTypes {'))
    if (releaseBlockIndex === -1) {
      throw new Error('Could not find the Expo release build type for DiceFrame release signing')
    }

    const signingIndex = contents.indexOf(debugReleaseSigning, releaseBlockIndex)
    if (signingIndex === -1) {
      throw new Error('Could not find the Expo release signing assignment for DiceFrame')
    }

    contents =
      contents.slice(0, signingIndex) +
      `            signingConfig diceframeHasReleaseSigning ? signingConfigs.release : signingConfigs.debug
` +
      `            if (!diceframeHasReleaseSigning) {
` +
      `                logger.warn('DiceFrame release build is using the Android debug key; configure DICEFRAME_UPLOAD_* for a distributable release.')
` +
      `            }
` +
      contents.slice(signingIndex + debugReleaseSigning.length)

    configWithGradle.modResults.contents = contents
    return configWithGradle
  })
}
