const { withAppBuildGradle } = require('@expo/config-plugins')

const PLUGIN_MARKER = '// DiceFrame ABI splits (generated by withAbiSplits)'

/**
 * APK 按 ABI 拆分构建：arm64-v8a / armeabi-v7a 两个瘦身包 + universal 全量包。
 * universal 包保持 DiceFrame-android.apk 发版通道不变（客户端「检查更新」固定
 * 优先下载它），拆分包供 Release 页按机型架构手动挑选。android/ 是 prebuild
 * 产物不入库，因此拆分配置必须走 config plugin，不能手改 build.gradle。
 */
module.exports = function withAbiSplits(config) {
  return withAppBuildGradle(config, (configWithGradle) => {
    if (configWithGradle.modResults.language !== 'groovy') {
      throw new Error('DiceFrame ABI splits requires a Groovy app/build.gradle')
    }

    let contents = configWithGradle.modResults.contents
    if (contents.includes(PLUGIN_MARKER)) {
      return configWithGradle
    }

    const androidBlock = 'android {\n    ndkVersion rootProject.ext.ndkVersion'
    if (!contents.includes(androidBlock)) {
      throw new Error('Could not find the Expo Android block for DiceFrame ABI splits')
    }

    contents = contents.replace(
      androidBlock,
      `${androidBlock}
${PLUGIN_MARKER}
    splits {
        abi {
            enable true
            reset()
            include "arm64-v8a", "armeabi-v7a"
            universalApk true
        }
    }`,
    )

    configWithGradle.modResults.contents = contents
    return configWithGradle
  })
}
